cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart:<int:product_id>/', views.Add_To_Cart, name='add_to_cart'),
    path('cart/', views.View_Cart, name='view_cart'),
    path('clear-cart/', views.Clear_Cart, name='clear_cart'),
    path('update-cart/', views.Update_Cart, name='update_cart'),
    path('cart-item-remove/<int:cart_item_id>/', views.Cart_Item_Remove, name='cart_item_remove'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('orders.urls')),
    path('', include('pet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('check-out/', views.CheckOut, name='CheckOut'),
    path('initiate_payment/', views.InitiatePayment, name='initiate_payment'),
    path('total_orders/', views.OrderByUser, name='orders_by_user'),
   

]

pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
	path('pet-tag/', views.PetView, name='pet_tag'),
	path('pet/<str:qr_code>/', views.PetQRView, name='pet_by_qr'),
	path('update-pet-tag/<int:id>/', views.UpdatePetProfile, name='update_pet_tag'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.Home, name='Home'),
    path('product/<slug:slug>/', views.Product_Details, name='Product_Details'),
    path('shop/', views.Shop, name='Shop'),
    path('category/<slug:slug>/', views.Category_Details, name='Category_Details'),
    path('search-result/', views.Search, name='search-products'),
    path('contact/', views.ContactUs, name='Contact'),
    path('about/', views.AboutUs, name='about'),


]

cart/models.py
from django.db import models
from store.models import Product
from accounts.models import Account
from django.utils import timezone
# Create your models here.



class Coupon(models.Model):
    code = models.CharField(max_length=150, unique=True)
    discount = models.PositiveIntegerField(help_text='Discount in percentage')
    active = models.BooleanField(default=False)
    active_date = models.DateField(help_text='Format: DD-MM-YEAR')
    expiry_date = models.DateField(help_text='Format: DD-MM-YEAR')
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

    def clean(self):
        current_time = timezone.now().date()
        if self.expiry_date < current_time and self.active_date > current_time:
            self.active = False 


class Cart(models.Model):
    cart_id = models.CharField(max_length=150, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.cart_id



class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.title

    def item_total(self):
        return float(self.product.price * self.quantity)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import Product
from .models import Cart, CartItem, Coupon
from django.utils import timezone
# Create your views here.

def _cart_id(request):

    cart_id = request.session.session_key
    if not cart_id:
        cart_id = request.session.create()
    return cart_id

def Add_To_Cart(request, product_id):
    current_user = request.user
    product =  get_object_or_404(Product, pk=product_id)
    

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))

        if current_user.is_authenticated:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
            except:
                cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.save()       

            cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()

            if cart_item_exist:
                cart_item = CartItem.objects.get(product=product, user=current_user)
                cart_item.quantity += quantity
                cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    user=current_user,
                    product=product, 
                    cart=cart,
                    quantity=quantity,
                    )

                cart_item.save()

        else:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
            except:
                cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.save()       

            cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()

            if cart_item_exist:
                cart_item = CartItem.objects.get(product=product, cart=cart)
                cart_item.quantity += quantity
                cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product, 
                    cart=cart,
                    quantity=quantity,
                    )

                cart_item.save()

    return redirect('cart:view_cart')


def View_Cart(request):
    current_user = request.user
    cart_items = None

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except:
        cart = Cart.objects.create(cart_id=_cart_id(request))

    if current_user.is_authenticated:
        cart_items = CartItem.objects.filter(user=current_user, is_active=True)
    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
    
    cart_total = 0
    sub_total = 0
    shipping_cost = 10

    for item in cart_items:
        sub_total += float(item.product.price * item.quantity)
    cart_total += shipping_cost + sub_total

    if cart.coupon and cart.coupon.active:
        discount_amount = ((cart_total / 100.00 ) * float(cart.coupon.discount))
        cart_total =cart_total - discount_amount
    else:
        discount_amount = 0
    context = {'cart_items':cart_items, 'cart_total':cart_total, 'sub_total':sub_total, 'cart_coupon': cart.coupon}

    return render(request, 'cart/shopping-cart.html', context)


def Clear_Cart(request):
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user)
        for cart_item in cart_items:
            cart_item.delete()
    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart.delete()
        except:
            cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.delete()

    return redirect('cart:view_cart')


def Update_Cart(request):
    current_time = timezone.now().date()

    if request.method == 'POST':
        coupon_code = request.POST.get('coupon_code')
        try:
            coupon = Coupon.objects.get(code=coupon_code)
        except:
            coupon = None
        if coupon is not None:
            if coupon.expiry_date > current_time and coupon.active:
                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                    cart.coupon = coupon
                    cart.save()
                except:
                    cart = Cart.objects.create(cart_id=_cart_id(request))
                    cart.coupon = coupon
                    cart.save()

            if coupon.active_date > current_time:
                return redirect('cart:view_cart')


        for key, value in request.POST.items():
            if key.startswith('quantity_'):
                cart_item_id = key.replace('quantity_', '')
                try:
                    cart_item = CartItem.objects.get(id=cart_item_id)
                    if cart_item.product.is_stock:
                        cart_item.quantity = int(value)
                        cart_item.save()
                except CartItem.DoesNotExist:
                    return redirect('cart:view_cart')
    
    return redirect('cart:view_cart')

def Cart_Item_Remove(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, pk=cart_item_id)
    cart_item.delete()
    return redirect('cart:view_cart')

templates/cart/shopping-cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart Items{% endblock %}


{% block content %}
{% if cart_items %}
    <!-- Page Add Section Begin -->
    <section class="page-add cart-page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>Cart<span>.</span></h2>
                        <a href="{% url 'store:Home' %}">Home</a>
                        <a class="active" href="{% url 'cart:view_cart' %}">Cart</a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'img/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Cart Page Section Begin -->
    <div class="cart-page">
        <form method="POST" action="{% url 'cart:update_cart' %}">
            {% csrf_token %}
        <div class="container">
            <div class="cart-table">
                <table>
                    <thead>
                        <tr>
                            <th class="product-h">Product</th>
                            <th>Price</th>
                            <th class="quan">Quantity</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                        <tr>
                            <td class="product-col">
                                <img src="{{item.product.image.url}}" alt="{{item.product.title}}" style="height: 120px; width: 150px;">
                                <div class="p-title">
                                    <h5>{{item.product.title}}</h5>
                                </div>
                            </td>
                            <td class="price-col">{{item.product.price}} BDT</td>
                            <td class="quantity-col">
                                {% if item.product.is_stock %}
                                <div class="pro-qty">
                                    <input type="text" value="{{item.quantity}}" name="quantity_{{ item.id }}">
                                </div>
                                {% else %}
                                <div class="p-title ml-4">
                                    <h5>Stock out</h5>
                                </div>
                                {% endif %}
                            </td>
                            <td class="total">{{item.item_total}} BDT</td>
                            <td class="product-close"><a href="{% url 'cart:cart_item_remove' item.id %}" style="color: inherit;">x</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="cart-btn">
                <div class="row">
                    <!-- <div class="col-lg-6">
                        {% if cart_coupon %}
                        {% if cart_coupon.active %}
                        <div class="coupon-input">
                            <input type="text" placeholder="{{cart_coupon}}" name="coupon_code" disabled>
                        </div>
                        {% else %}
                        <div class="coupon-input">
                            <input type="text" placeholder="{{cart_coupon}} -- expired" name="coupon_code" disabled>
                        </div>
                        {% endif %}
                        {% else %}
                        <div class="coupon-input">
                            <input type="text" placeholder="Enter coupon code" name="coupon_code">
                        </div>
                        {% endif %}
                    </div> -->
                    <div class="col-lg-12 text-left text-lg-right">
                        <div class="site-btn clear-btn"><a href="{% url 'cart:clear_cart' %}" style="color: inherit;">Clear Cart</a></div>
                        <button type="submit" id="updateCartBtn" class="site-btn update-btn" style="color: inherit; background-color: white;">Update Cart</button>

                        
                    </div>
                </div>
            </div>
        </div>
        </form>
        <div class="shopping-method">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                       
                        <div class="total-info">
                            <div class="total-table">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Subtotal</th>
                                            <th>Shipping</th>
                                            <th class="total-cart">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="sub-total">{{sub_total}} BDT</td>
                                            <td class="shipping">10 BDT</td>
                                            <td class="total-cart-p">{{cart_total|floatformat:2}} BDT</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 text-right">
                                    <a href="{% url 'orders:CheckOut' %}" class="primary-btn chechout-btn">Proceed to checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart Page Section End -->
    
    {% else %}
    <div class="container" style="height: 60%;">
        <div class="row">
            <div class="col-lg-12" >
                {% include 'includes/no-result.html' %}
            </div>    
        </div>
    </div>

    {% endif %}

    {% endblock %}