accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('account-login/', views.Log_In, name ='login'),
    path('account-logout/', views.Log_Out, name='logout'),
    path('account-register/', views.Sign_Up, name='signup'),
    path('reset-password/', views.Reset_Password, name='reset_password'),

    path('activate/<uidb64>/<token>/', views.Activate, name='activate'),
    path('reset_password_validate/<uidb64>/<token>/', views.Reset_Password_Validate, name='reset_password_validate'),
    path('reset_password_process/', views.Reset_Password_Process, name='reset_password_process'),
    path('change_password/', views.Change_Password, name='change_password'),

    path('account-user-profile/', views.DashBoard, name='dashboard'),
    path('update-profile/', views.Update_Profile, name='update_profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('orders.urls')),
    path('', include('pet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('check-out/', views.CheckOut, name='CheckOut'),
    path('initiate_payment/', views.InitiatePayment, name='initiate_payment'),
    path('total_orders/', views.OrderByUser, name='orders_by_user'),
   

]

pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
	path('pet-tag/', views.PetView, name='pet_tag'),
	path('pet/<str:qr_code>/', views.PetQRView, name='pet_by_qr'),
	path('update-pet-tag/<int:id>/', views.UpdatePetProfile, name='update_pet_tag'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class MyAccountManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):

        if not email:
            raise ValueError('User must have an email address.')


        user = self.model(

            email=self.normalize_email(email),
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        username = email.split('@')[0]

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superadmin', True)
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_active', True)
        extra_fields['username'] = username

        if extra_fields.get('is_staff') is not True:
            raise ValueError(('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superadmin') is not True:
            raise ValueError(('is_superadmin must have is_superadmin=True.'))
        return self.create_user(email=email, password=password, **extra_fields)


class Account(AbstractBaseUser):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = ['first_name', 'last_name', 'username', 'password', 'confirm_password']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def profile_image(self):
        userprofile =  UserProfile.objects.get(user=self)
        return userprofile.profile_image





class UserProfile(models.Model):
    
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True)
    address_line = models.CharField(blank=True, max_length=200)
    profile_image = models.ImageField(upload_to='photos/user/profile', default='photos/default/default_user.png')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=30)

    def __str__(self):
        return self.user.email



@receiver(post_save, sender=Account)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = UserProfile.objects.create(user=instance)
        user_profile.save()

accounts/forms.py
from .models import Account, UserProfile
from django import forms




class RegistrationForm(forms.ModelForm):

	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))

	class Meta:
		model = Account
		fields = ['first_name','last_name','username', 'email', 'password']



	def clean(self):	
		cleaned_data = super(RegistrationForm, self).clean()
		password = cleaned_data.get('password')
		confirm_password = cleaned_data.get('confirm_password')

		if password != confirm_password:
			raise forms.ValidationError('Password does not match!')
		
		username = cleaned_data.get('username')
		try:
			flag = Account.objects.get(username=username).exists()
			if flag:
				raise forms.ValidationError('Username already used.')
		except:
			pass

			

	def __init__(self, *args, **kwargs):
		super(RegistrationForm, self).__init__(*args, **kwargs)

		self.fields['first_name'].widget.attrs['placeholder']='First Name'
		self.fields['last_name'].widget.attrs['placeholder']='Last Name'
		self.fields['username'].widget.attrs['placeholder']='username'
		self.fields['email'].widget.attrs['placeholder']='email'
		

		for field in self.fields:
			self.fields[field].widget.attrs['class'] = 'form-control'

class UserForm(forms.ModelForm):

	class Meta:

		model = Account
		fields = ['first_name', 'last_name']

	def __init__(self, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)

		self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
		self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'

		for field in self.fields:
			self.fields[field].widget.attrs['class']= 'form-control'

class UserProfileForm(forms.ModelForm):
	
	profile_image = forms.ImageField(required=False, error_messages={'Invalid':('Image Files Only.')}, widget=forms.FileInput)
	class Meta:
		model = UserProfile
		fields = ['phone', 'address_line', 'profile_image', 'city', 'state', 'country']

	def __init__(self, *args, **kwargs):
		super(UserProfileForm, self).__init__(*args, **kwargs)

		self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
		self.fields['address_line'].widget.attrs['placeholder'] = 'Address'
		self.fields['city'].widget.attrs['placeholder'] = 'City'
		self.fields['state'].widget.attrs['placeholder'] = 'State'
		self.fields['country'].widget.attrs['placeholder'] = 'Country'

		for field in self.fields:
			self.fields[field].widget.attrs['class']= 'form-control'

accounts/views.py
from django.shortcuts import render, redirect, reverse
from .models import Account, UserProfile
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, UserForm, UserProfileForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages, auth
from cart.views import _cart_id
from cart.models import Cart, CartItem
from pet.models import PetTag
# Create your views here.

def Log_In(request):
    if request.user.is_authenticated:
        messages.warning(request, 'You are already logged in.')
        return redirect('store:Home')
    else:
        if request.method == 'POST':
            email = request.POST['email']
            password = request.POST['password']
            user = auth.authenticate(email=email, password=password)
            if user is not None:

                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                except:
                    cart = Cart.objects.create(cart_id=_cart_id(request))
                
                is_cart_item_exist = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exist:
                    cart_item = CartItem.objects.filter(cart=cart)

                    for item in cart_item:
                        item.user = user
                        item.save()

                auth.login(request, user)
                messages.success(request, 'Logged in succesfully.')
                
                return redirect('store:Home')

    return render(request, 'accounts/login.html')


@login_required(login_url='accounts:login')
def Log_Out(request):
	if request.user.is_authenticated:
		auth.logout(request)
		messages.success(request, 'You are now logged out.')
	else:
		messages.warning(request, 'You are already logged out.')
		return redirect('accounts:login')
	return redirect('accounts:login')


def Sign_Up(request):
    form = RegistrationForm()
    if request.user.is_authenticated != True:
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']

                user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, password=password, username=username)
                user.save()

                to_mail = email
                current_site = get_current_site(request)
                mail_subject = 'Please active your account'
                mail_messages = render_to_string('accounts/accounts_verification_email.html', {

				'user':user,
				'domain':current_site,
				'uid':urlsafe_base64_encode(force_bytes(user.pk)),
				'token':default_token_generator.make_token(user),

				})

                email_send = EmailMessage(mail_subject, mail_messages, settings.EMAIL_HOST_USER, to=[to_mail])
                email_send.fail_silently = False
                email_send.send()
                
                url = reverse('accounts:login') + f'?command=verification&email={email}'
                return redirect(url)
  
    else:
        return redirect('accounts:login')
    
    context = {'form':form}
    return render(request, 'accounts/register.html', context)



def Activate(request, uidb64, token):
	
	try:
		uid = urlsafe_base64_decode(uidb64).decode()
		user = Account._default_manager.get(pk=uid)
	except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
		user = None

	if user is not None and default_token_generator.check_token(user, token):
		user.is_active = True
		user.save()
		messages.success(request, 'Congratulations! Your account is activated.')
		return redirect('accounts:login')

	else:
		messages.error(request, 'Invalid activation link.')
		return redirect('accounts:register')

def Reset_Password(request):
    if request.method == 'POST':
        email = request.POST['email']

        if Account.objects.filter(email__iexact=email).exists():
            user  = Account.objects.filter(email__iexact=email)[0]
            current_site = get_current_site(request)
            to_mail = email
            mail_subject = 'Reset your password.'
            mail_messages = render_to_string('accounts/reset_password_email.html', {

			'user':user,
			'domain':current_site,
			'uid':urlsafe_base64_encode(force_bytes(user.pk)),
			'token':default_token_generator.make_token(user),

			})

            send_mail = EmailMessage(mail_subject, mail_messages, to=[to_mail])
            send_mail.fail_silently = False
            send_mail.send()
            messages.success(request, 'Password reset email has been send to your email address.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'No account associated with this email.')
            return redirect('accounts:login')
    
    return render(request, 'accounts/reset_password.html')


def Reset_Password_Validate(request, uidb64, token):
    
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
        
    except(ValueError, TypeError, OverflowError, Account.DoesNotExist):
        user = None
        
    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password.')
        return redirect('accounts:reset_password_process')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:log_in')

def Reset_Password_Process(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            return redirect('accounts:login')
        else:
            messages.error('Password did not match.')
            return redirect('accounts:reset_password')

    return render(request, 'accounts/new_password.html')

@login_required(login_url='accounts:login')
def DashBoard(request):
    current_user = request.user
    userprofile = UserProfile.objects.get(user=current_user)
    pets = PetTag.objects.filter(user=request.user)

    context = {'current_user':current_user, 'userprofile':userprofile, 'pets':pets}
    return render(request, 'accounts/profle.html', context)

@login_required(login_url='accounts:login')
def Update_Profile(request):
    userprofile = UserProfile.objects.get(user=request.user)
    userform = UserForm(instance=request.user)
    userprofileform = UserProfileForm(instance=userprofile)
    if request.method == 'POST':

        try:
            userform = UserForm(request.POST, instance=request.user)
            userprofileform = UserProfileForm(request.POST, request.FILES, instance=userprofile)
            if userform.is_valid() & userprofileform.is_valid():
                userform.save()
                userprofileform.save()
                messages.success(request, 'Profile information has been updated.')
                return redirect('accounts:dashboard')
        except:
            userform = UserForm(instance=request.user)
            userprofileform = UserProfileForm(instane=userprofile)

    context = {'userform':userform, 'userprofileform':userprofileform}

    return render(request, 'accounts/update_profile.html', context)

@login_required(login_url='accounts:login')
def Change_Password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        user = Account.objects.get(email=request.user.email)
        if new_password == confirm_password:
            authorized = user.check_password(current_password)
            if authorized:
                user.set_password(new_password)
                user.save()
                auth.logout(request)
                messages.success(request, 'Your password has been updated, login to continue!')
                return redirect('accounts:login')
            else:
                messages.error(request, 'Your current password does not match.')
                return redirect('accounts:change_password')


        else:
            messages.error(request, 'Confirm password does not match.')
            return redirect('accounts:change_password')
    return render(request, 'accounts/change_password.html')

templates/accounts/accounts_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to active your account.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ingore this email.

{% endautoescape %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Dashboard {% endblock %}

{% block content %} 


    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'img/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->


    <!-- Dashboard Content Section Begin -->
    <div class="contact-section" style="margin-top: 10px;">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-12">
                    <div class="contact-form">
                        <img src="{{ userprofile.profile_image.url }}" alt="Profile Image" class="img-fluid rounded-circle" style="height: 150px; width: 150px; margin-bottom: 20px;">
                        <h4 style="margin-top: 5px;">{{ current_user.first_name }} {{ current_user.last_name }}</h4>
                        <div class="col-lg-12 text-center mb-20">
                        <p><strong>Username</strong>: {{ current_user.username }}</p>
                        <p><strong>Email</strong>: {{ current_user.email }}</p>
                        <p><strong>Phone:</strong>{% if userprofile.phone %}{{userprofile.phone}}{% else %} N/A {% endif %}</p>
                        <p><strong>Address:</strong> {% if userprofile.address_line %}
                            {{ userprofile.address_line }}, {{ userprofile.city }}, {{ userprofile.state }}, {{ userprofile.country }}</p>
                            {% else %}
                                N/A
                            {% endif %}
                        </div>
                        <div class="row">
                            <div class="col-lg-6 text-center">
                                <a href="{% url 'accounts:update_profile' %}">
                                <button class="btn-block" type="submit">Update Profile</button>
                                </a>
                            </div>
                            <div class="col-lg-6 text-center">
                                <a href="">
                                <button class="btn-block" type="submit">Orders</button>
                                </a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Dashboard Content Section End -->


{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Account {% endblock %}

{% block content %} 


    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-12  text-center">
                    <div class="page-breadcrumb">
                        <h3>Login To Your Account<span>.</span></h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Contact Section Begin -->
    <div class="contact-section">
        <div class="login-container">
            <div class="row">
                <div>
                    <form action="{% url 'accounts:login' %}" class="contact-form" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12 py-2">
                                <input type="email" placeholder="email" name="email">
                            </div>
                            <div class="col-lg-12 py-2">
                                <input type="password" placeholder="password" name="password">
                            </div>
                            <div class="col-lg-12 text-right">
                                <button class="btn-block" type="submit">Login</button>
                            </div>
                            <div class="col-lg-12 my-2 text-center">
                                <p>
                                    Don't have an account ?
                                    <strong><a href="{% url 'accounts:signup' %}" class="text-decoration-none text-dark">Sign Up Here</a></strong>
                                </p>
                            </div>
                            <div class="col-lg-12 text-center">
                                <p>
                                    Lost your password !
                                    <strong><a href="{% url 'accounts:reset_password' %}" class="text-decoration-none text-dark">Reset Password</a></strong>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Contact Section End -->


{% endblock %}

templates/accounts/profle.html
{% extends 'base.html' %}
{% load static %}
{% block title %} My Profile - AmarPet {% endblock %}
{% block style %}
    <style>
        body {
            background-color: #f9f9f9;
            font-family: "Outfit", sans-serif;
            color: #333;
            line-height: 1.6;
        }
        
        nav {
            font-size: 0.9rem;
            color: #666;
        }
        nav strong {
            color: #333;
        }
        .profile-section {
            background: #fff;
            border-radius: 12px;
            padding: 20px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }
        .profile-header {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
        }
        .profile-avatar {
            width: 80px;
            height: 80px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 20px;
        }
        .profile-name {
            font-size: 1.5rem;
            font-weight: bold;
            color: #333;
        }
        .profile-email {
            font-size: 0.9rem;
            color: #666;
        }
        .profile-info p {
            margin: 5px 0;
            font-size: 0.9rem;
        }
        .profile-info strong {
            color: #333;
        }
        .btn-edit-profile {
            background: var(--pcolor);
            color: white;
            border: none;
            padding: 8px 16px;
            border-radius: 20px;
            font-size: 0.9rem;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        .btn-edit-profile:hover {
            background: var(--hcolor);
        }
        .order-history-link {
            color: var(--bcolor);
            text-decoration: none;
            font-weight: bold;
        }
        .order-history-link:hover {
            text-decoration: underline;
            color: var(--bcolor);
        }
    </style>
{% endblock %}

{% block content %} 
    <div class="container pt-5">
        <!-- Breadcrumb -->
        <nav class="mb-3 fs-5">
            <span>Home > My Account > <strong>My Profile</strong></span>
        </nav>

        <!-- Profile Section -->
        <div class="profile-section">
            <div class="profile-header">
                {% if userprofile %}
                <img src="{{userprofile.profile_image.url}}" alt="Profile Avatar" class="profile-avatar">
                {% else %}
                <img src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dXNlcnxlbnwwfHwwfHx8MA%3D%3D" alt="Profile Avatar" class="profile-avatar">
                {% endif %}
                <div>
                    <p class="profile-name">{{ current_user.first_name }} {{ current_user.last_name }}</p>
                    <p class="profile-email">{{ current_user.email }}</p>
                </div>
            </div>
            <hr>
            <div class="profile-info">
                <p><strong>Phone:</strong> {% if userprofile.phone %}{{userprofile.phone}}{% else %} N/A {% endif %}</p>
                <p><strong>Address:</strong>
                    {% if userprofile.address_line %}
                        {{ userprofile.address_line }}, {{ userprofile.city }}, {{ userprofile.state }}, {{ userprofile.country }}
                    {% else %}
                        N/A
                    {% endif %}
                </p>
                <p><strong>Member Since:</strong> {{current_user.date_joined}}</p>
            </div>
            <a href="{% url 'accounts:update_profile' %}">
                <button class="btn-edit-profile mt-3">Edit Profile</button>
            </a>

            {% if pets %}
                {% for pet in pets %}
                    <a href="{% url 'pet:update_pet_tag' pet.id %}">
                        <button class="btn-edit-profile mt-3">Edit {{pet.pet_name}} Profile</button>
                    </a>
                {% endfor %}
            {% endif %}
        </div>

        <!-- Order History Section -->
        <div class="profile-section">
            <h5 class="mb-3">Order History</h5>
            <p>You can view your past orders by visiting the <a href="{% url 'orders:orders_by_user' %}" class="order-history-link">My Orders</a> page.</p>
        </div>

        <!-- Account Settings Section -->
        <div class="profile-section">
            <h5 class="mb-3">Account Settings</h5>
            <ul style="list-style-type: none; padding: 0;">
                <li class="mb-2"><a href="{% url 'accounts:change_password' %}" class="order-history-link">Change Password</a></li>
            </ul>
        </div>
    </div>


{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register Yourself {% endblock %} 

{% block content %}  
  
  <!-- Page Add Section Begin -->
  <section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h3>Get Registered<span>.</span></h3>
                </div>
            </div>
            <div class="col-lg-8">
                <img src="{% static 'img/add.jpg' %}" alt="">
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->

<!-- Contact Section Begin -->
<div class="contact-section">
    <div class="register-container">
        <div class="row">
            <div class="col-lg-12">
                <form action="{% url 'accounts:signup' %}" class="contact-form" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                           {{form.first_name}}
                        </div>
                        <div class="col-lg-6">
                            {{form.first_name}}
                        </div>
                        <div class="col-lg-12 py-2">
                          {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="col-lg-12 py-2">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="col-lg-6">
                            {{form.password}}
                            {{ form.password.errors }}
                        </div>
                        <div class="col-lg-6">
                            {{form.confirm_password}}
                            {{ form.confirm_password.errors }}
                        </div>
                        <div class="col-lg-12 text-right">
                            <button class="btn-block" type="submit">Register</button>
                        </div>
                        <div class="col-lg-12 my-2 text-center">
                            <p>
                                Already have an account ?
                                <strong><a href="{% url 'accounts:login' %}" class="text-decoration-none text-dark">Login Here</a></strong>
                            </p>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>
<!-- Contact Section End -->


{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}} {{user.last_name}},

As requested, please click below link ti reset your password.
http://{{domain}}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

If you think it's not you. please ignore this mail.

{% endautoescape %}