accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('account-login/', views.Log_In, name ='login'),
    path('account-logout/', views.Log_Out, name='logout'),
    path('account-register/', views.Sign_Up, name='signup'),
    path('reset-password/', views.Reset_Password, name='reset_password'),

    path('activate/<uidb64>/<token>/', views.Activate, name='activate'),
    path('reset_password_validate/<uidb64>/<token>/', views.Reset_Password_Validate, name='reset_password_validate'),
    path('reset_password_process/', views.Reset_Password_Process, name='reset_password_process'),
    path('change_password/', views.Change_Password, name='change_password'),

    path('account-user-profile/', views.DashBoard, name='dashboard'),
    path('update-profile/', views.Update_Profile, name='update_profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart:<int:product_id>/', views.Add_To_Cart, name='add_to_cart'),
    path('cart/', views.View_Cart, name='view_cart'),
    path('clear-cart/', views.Clear_Cart, name='clear_cart'),
    path('update-cart/', views.Update_Cart, name='update_cart'),
    path('cart-item-remove/<int:cart_item_id>/', views.Cart_Item_Remove, name='cart_item_remove'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('orders.urls')),
    path('', include('pet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
	path('pet-tag/', views.PetView, name='pet_tag'),
	path('pet/<str:qr_code>/', views.PetQRView, name='pet_by_qr'),
	path('update-pet-tag/<int:id>/', views.UpdatePetProfile, name='update_pet_tag'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.Home, name='Home'),
    path('product/<slug:slug>/', views.Product_Details, name='Product_Details'),
    path('shop/', views.Shop, name='Shop'),
    path('category/<slug:slug>/', views.Category_Details, name='Category_Details'),
    path('search-result/', views.Search, name='search-products'),
    path('contact/', views.ContactUs, name='Contact'),
    path('about/', views.AboutUs, name='about'),


]

templates/includes/footer.html
{% load static %}
<!-- Footer Section Begin -->
<footer class="footer-section spad">
    <div class="container">
        <div class="footer-widget">
            <div class="row">
                <div class="col-lg-4 col-sm-8" style="justify-content: center; display: flex; justify-items: center;">
                    <div class="single-footer-widget">
                        <h4><img src="{% static 'kedi.jpg' %}"></h4>
                        <ul>
                            <li>
                                <p style="color: white;">Your pet's happiness is our priority. Kedismart delivers quality pet supplies and expert advice directly to you. We offer a wide range of products to ensure your pets thrive. Join our community and experience the convenience of online pet care. Copyright © 2025 Kedismart.</p>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-8" style="justify-content: left; display: flex; justify-items: left;">
                    <div class="single-footer-widget">
                        <h4>Quick Links</h4>
                        <ul>
                            <li><a href="{% url 'store:Home' %}" style="color: white;">Home</a></li>
                            <li><a href="{% url 'store:about' %}" style="color: white;">About Us</a></li>
                            <li><a href="{% url 'store:Shop' %}" style="color: white;">Shop</a></li>
                            <li><a href="{% url 'pet:pet_tag' %}" style="color: white;">Pet Tag</a></li>
                            <li><a href="{% url 'store:Contact' %}" style="color: white;">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-8" style="justify-content: left; display: flex; justify-items: left;">
                    <div class="single-footer-widget">
                        <h4>Category Links</h4>
                        <ul>
                            {% for category in categories %}
                            <li><a href="{% url 'store:Category_Details' category.slug %}" style="color: white;">{{category.title|title}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="social-links-warp">
        <div class="container">
            <div class="social-links" style="justify-items: center; justify-content: center; display: flex;">

                <a href="{{store_details.instagram}}" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                <a href="{{store_details.faecbook}}" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                <a href="{{store_details.twitter}}" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                <a href="{{store_details.youtube}}" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
            </div>
        </div>
    </div>

<div class="container text-center pt-5">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Application is made <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://github.com/sohan-me" target="_blank">Noob</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        </div>


    </div>
</footer>
<!-- Footer Section End -->

templates/includes/header.html
 {% load static %}
 
 <!-- Header Section Begin -->
 <header class="header-section">
    <div class="container-fluid">
        <div class="inner-header">
            <div class="logo">
                <a href="{% url 'store:Home' %}"><img src="{% static 'kedi.png' %}" alt=""></a>
            </div>
            <div class="header-right">
                <img src="{% static 'img/icons/search.png' %}" alt="" class="search-trigger">
                <a href="{% url 'accounts:dashboard' %}" style="margin-right: 20px;">
                    <img src="{% static 'img/icons/man.png' %}" alt="">
                </a>
                <a href="{% url 'cart:view_cart' %}">
                    <img src="{% static 'img/icons/bag.png' %}" alt="">
                    <span>{% if cart_count %} {{cart_count}} {% else %} 0 {% endif %}</span>
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="user-access">
                <a href="{% url 'accounts:logout' %}" class="a-btn">Logout</a>
            </div>
            {% else %}
            <div class="user-access">
                <a href="{% url 'accounts:signup' %}" class="a-btn">Register</a>
                <a href="{% url 'accounts:login' %}" class="in a-btn">Sign in</a>
            </div>
            {% endif %}
           
            <nav class="main-menu mobile-menu">
                <ul>
                    <li><a class="{% if request.path == '/' %}active{% endif %}" href="{% url 'store:Home' %}">Home</a></li>
                    <li><a class="{% if request.path == '/pet-tag/' %}active{% endif %}" href="{% url 'pet:pet_tag' %}">Smart Pet Tag</a></li>
                    <li><a class="{% if request.path == '/shop/' %}active{% endif %}" href="{% url 'store:Shop' %}">Shop</a></li>
                    <li><a href="" class="{% if 'category' in request.path %}active{% endif %}">By Category</a>
                        <ul class="sub-menu">
                            {% for category in categories %}
                            <li><a href="{% url 'store:Category_Details' category.slug %}">{{category.title|title}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li><a href="{% url 'store:about' %}" class="{% if request.path == '/about/' %}active{% endif %}">About</a></li>
                    <li><a href="{% url 'store:Contact' %}" class="{% if request.path == '/contact/' %}active{% endif %}">Contact</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>


<!-- Header Info Begin -->
<!-- <div class="header-info">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="header-item">
                    <img src="{% static 'img/icons/delivery.png' %}" alt="">
                    <p>Free shipping on orders</p>
                </div>
            </div>
            <div class="col-md-4 text-left text-lg-center">
                <div class="header-item">
                    <img src="{% static 'img/icons/voucher.png' %}" alt="">
                    <p>20% Student Discount</p>
                </div>
            </div>
            <div class="col-md-4 text-left text-xl-right">
                <div class="header-item">
                <img src="{% static 'img/icons/sales.png' %}" alt="">
                <p>30% off on dresses. Use code: 30OFF</p>
            </div>
            </div>
        </div>
    </div>
</div> -->
<!-- Header Info End -->
<!-- Header End -->

templates/includes/no-result.html
{% load static %}

<div class="row justify-content-center align-item-center">
    <div class="col-md-5">
        <img class="image-fluid" src="{% static 'img/no-result.jpg' %}" style="width: 420px;" alt="no-result">
    </div>
</div>

<div class="more-product">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h5 class="mb-3">Sorry, No Products Here !</h5>
            <a href="{% url 'store:Home' %}" class="primary-btn">Go Back</a>
        </div>
    </div>
</div>

templates/includes/pagination.html
<div class="cf-right">
    <span>{{ p_count }} Products</span>
    
    {% if products.has_previous %}
        <a href="?page={{ products.previous_page_number }}"><</a>
    {% endif %}
    
    {% for i in products.paginator.page_range %}
        <a href="?page={{ i }}" {% if products.number == i %}class="active"{% endif %}>{{ i }}</a>
    {% endfor %}
    
    {% if products.has_next %}
        <a href="?page={{ products.next_page_number }}">></a>
    {% endif %}
</div>

templates/includes/search.html
 <!-- Search model -->
 <div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" method="GET" action="{% url 'store:search-products' %}">
            <input type="text" id="search-input" placeholder="Search here....." name="key">
        </form>
    </div> 
</div>
<!-- Search model end -->

templates/includes/slider.html
{% load static %}
<section class="hero-slider">
    <div class="hero-items owl-carousel">
        {% for slider in slider %}
        <div class="single-slider-item set-bg" data-setbg="{{ slider.banner.url }}" style="min-height: 600px;">
            <div class="container">
                <div class="row">
                   <!--  <div class="col-lg-12">
                        <h1>{{slider.initial_part}}</h1>
                        <h2>{{slider.final_part}}</h2>
                        <a href="{% url 'store:Shop' %}" class="primary-btn">See More</a>
                    </div> -->
                </div>
            </div>
        </div>
        {% endfor %}
        
    </div>
</section>