cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart:<int:product_id>/', views.Add_To_Cart, name='add_to_cart'),
    path('cart/', views.View_Cart, name='view_cart'),
    path('clear-cart/', views.Clear_Cart, name='clear_cart'),
    path('update-cart/', views.Update_Cart, name='update_cart'),
    path('cart-item-remove/<int:cart_item_id>/', views.Cart_Item_Remove, name='cart_item_remove'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('orders.urls')),
    path('', include('pet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

pet/urls.py
from django.urls import path
from . import views

app_name = 'pet'

urlpatterns = [
	path('pet-tag/', views.PetView, name='pet_tag'),
	path('pet/<str:qr_code>/', views.PetQRView, name='pet_by_qr'),
	path('update-pet-tag/<int:id>/', views.UpdatePetProfile, name='update_pet_tag'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.Home, name='Home'),
    path('product/<slug:slug>/', views.Product_Details, name='Product_Details'),
    path('shop/', views.Shop, name='Shop'),
    path('category/<slug:slug>/', views.Category_Details, name='Category_Details'),
    path('search-result/', views.Search, name='search-products'),
    path('contact/', views.ContactUs, name='Contact'),
    path('about/', views.AboutUs, name='about'),


]

templates/product/categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{category.title|title}} {% endblock %}

{% block content %}

    {% if p_count > 0 %}
    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>{{category.title|title}}<span>.</span></h2>
                        <a href="{% url 'store:Home' %}">Home</a>
                        <a class="active" href="{% url 'store:Category_Details' category.slug %}">Category / {{category.slug|title}}</a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'img/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    {% endif %}

    <!-- Categories Page Section Begin -->
    <section class="categories-page spad">
        <div class="container">
            <div class="categories-controls">
                {% if p_count > 0 %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="categories-filter">                                                 
                            {% include 'includes/pagination.html' %}
                        </div>
                    </div>
                </div>
                {% endif %}
                
            </div>
            {% if p_count > 0 %}
            <div class="row">
                
                {% for product in products %}
                <div class="col-lg-3 col-md-3">
                    <div class="single-product-item">
                        <figure>
                            <img src="{{product.image.url}}" alt="" style="height: 250px; width: 250px;">
                            {% if product.featured %}
                            <div class="p-status">Featured</div>
                            {% endif %}
                            <div class="hover-icon">
                                <a href="{{product.image.url}}" class="pop-up"><img src="{% static 'img/icons/zoom-plus.png' %}"
                                        alt=""></a>
                            </div>
                        </figure>
                        <div class="product-text">
                            <a href="{% url 'store:Product_Details' product.slug %}">
                                <h6>{{product.title|truncatewords:6}}</h6>
                            </a>
                            <p>${{product.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
                {% else %}
                    {% include 'includes/no-result.html' %}
                    
                 {% endif %}
            </div>
        </div>
    </section>
    <!-- Categories Page Section End -->

{% endblock %}

templates/product/product-page.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{product.title}} {% endblock %}


{% block content %}
    
    
    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>Shirts<span>.</span></h2>
                        <a href="#">Home</a>
                        <a href="#">Dresses</a>
                        <a class="active" href="#">Night Dresses</a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'img/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    <!-- Product Page Section Beign -->
    <section class="product-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="product-slider owl-carousel">
                        <div class="product-img" style="width: 80%;">
                            <figure>
                                <img style="height: 380px;" src="{{product.image.url}}" alt="">
                                {% if product.featured %} <div class="p-status"> Featured </div> {% endif %}
                            </figure>
                        </div>
                       
                    </div>
                    
                </div>
                <div class="col-lg-6">
                    <div class="product-content">
                        <h2>{{product.title}}</h2>
                        <div class="pc-meta">
                            <h5>${{product.price}}</h5>
                            {% if product.is_stock %}
                            <div class="p-status">
                                In Stock
                            </div>
                            {% else %}
                            <div class="p-status mb-2" >
                                Out of Stock
                            </div>
                            {% endif %}
                            <div class="rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                        </div>
                        <p>{{product.description}}</p>
                        <ul class="tags">
                            <li><span>Category :</span> {{product.category|title}}</li>
                        </ul>

                        {% if product.is_stock %}
            
                        <form method="POST" action="{% url 'cart:add_to_cart' product.id %}">
                            {% csrf_token %}
                            <div class="product-quantity">
                                <div class="pro-qty">
                                    <input type="number" name="quantity" value="1" min="1">
                                </div>
                            </div>
                            {% if product.is_stock %}
                                <button type="submit" class="primary-btn a-btn">Add to cart</button>
                            {% else %}
                                <button type="button" class="primary-btn pc-btn" disabled>Out of stock</button>
                            {% endif %}
                        </form>
                        {% endif %}
                        <ul class="p-info">
                            <li>Product Information</li>
                            <li>Reviews</li>
                            <li>Product Care</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Page Section End -->

    <!-- Related Product Section Begin -->
    <section class="related-product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-title">
                        <h2>Related Products</h2>
                    </div>
                </div>
            </div>
            <div class="row">

                {% for r_product in relatable_product %}
                <div class="col-lg-3 col-sm-6">
                    <div class="single-product-item">
                        <figure>
                            <a href="{% url 'store:Product_Details' r_product.slug %}"><img src="{{r_product.image.url}}" style="height: 300px;" alt=""></a>
                            {% if r_product.featured %} <div class="p-status"> Featured </div> {% endif %}
                        </figure>
                        <div class="product-text">
                            <h6>{{r_product.title|truncatewords:6}}</h6>
                            <p>${{r_product.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
            </div>
        </div>
    </section>
    <!-- Related Product Section End -->


    {% endblock %}

templates/product/shop.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Shop {% endblock %}

{% block content %}

    {% if p_count > 0 %}
    <!-- Page Add Section Begin -->
    <section class="page-add">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="page-breadcrumb">
                        <h2>Shop<span>.</span></h2>
                        <a href="{% url 'store:Home' %}">Home </a>
                        <a class="active" href="{% url 'store:Shop' %}"> Shop</a>
                    </div>
                </div>
                <div class="col-lg-8">
                    <img src="{% static 'img/add.jpg' %}" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- Page Add Section End -->

    {% endif %}

    <!-- Categories Page Section Begin -->
    <section class="categories-page spad">
        <div class="container">
            <div class="categories-controls">
                {% if p_count > 0 %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="categories-filter">                                                 
                            {% include 'includes/pagination.html' %}
                        </div>
                    </div>
                </div>
                {% endif %}
                
            </div>
            {% if p_count > 0 %}
            <div class="row">
                
                {% for product in products %}
                <div class="col-lg-3 col-md-3">
                    <div class="single-product-item">
                        <figure>
                            <img src="{{product.image.url}}" alt="" style="height: 250px; width: 250px;">
                            {% if product.featured %}
                            <div class="p-status">Featured</div>
                            {% endif %}
                            <div class="hover-icon">
                                <a href="{{product.image.url}}" class="pop-up"><img src="{% static 'img/icons/zoom-plus.png' %}"
                                        alt=""></a>
                            </div>
                        </figure>
                        <div class="product-text">
                            <a href="{% url 'store:Product_Details' product.slug %}">
                                <h6>{{product.title|truncatewords:6}}</h6>
                            </a>
                            <p>${{product.price}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
                {% else %}
                    {% include 'includes/no-result.html' %}
                    
                 {% endif %}
            </div>
        </div>
    </section>
    <!-- Categories Page Section End -->

{% endblock %}